- type: latheRecipe
  parent: BaseAmmoRecipe
  id: StripperClip
  result: SpeedLoaderLightRifle
  materials:
    Steel: 100

- type: latheRecipe
  id: SecurityBola
  result: SecurityBola
  completetime: 2
  materials:
    Steel: 400

#Modern Warfare 4: Sec edition
- type: latheRecipe
  id: ClothingOuterCombatArmor
  result: ClothingOuterCombatArmor
  materials:
    Steel: 500
    Plastic: 400
    Cloth: 1500
    Silver: 200

- type: latheRecipe
  id: ClothingHeadCombatHelmet
  result: ClothingHeadCombatHelmet
  materials:
    Steel: 500
    Plastic: 400
    Cloth: 1000
    Silver: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponEnergyCarbineHarmony
  result: WeaponEnergyCarbineHarmony
  completetime: 6
  materials:
    Steel: 800
    Glass: 400
    Plastic: 300

- type: latheRecipe
  id: EnergyCartridgePrintedHarmony
  result: EnergyCartridgePrintedHarmony
  completetime: 2
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 250

- type: latheRecipe
  id: EnergyCartridgeUnstablePrintedHarmony
  result: EnergyCartridgeUnstablePrintedHarmony
  completetime: 2
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 250
    Gold: 300
    Plasma: 500

- type: latheRecipe
  id: EnergyCartridgeXRayPrintedHarmony
  result: EnergyCartridgeXRayPrintedHarmony
  completetime: 2
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 250
    Uranium: 300